const Data = [
    {
        id: 1,
        image: "https://images.deepai.org/art-image/c749c01c06dd47208ae1ff919b853e8b/perfume-name-lethered-gold.jpg",
        name: "Mystic Oud",
        color: "Black",
        type:"mild",
        price: 3500,
        dealOfTheDayPrice: 3300,
        brand: "Oud Essence",
        outfit: "Men",
        description: "Mystic Oud is a deep, rich fragrance that combines the earthy notes of oud with spicy hints of saffron and a touch of amber. Ideal for evening wear or special occasions, this perfume exudes sophistication and mystery.",
        rating: 4.8,
        reviewNumber: 200,
        availability: "In stock",
        stock: 10
    },
    {
        id: 2,
        image: "https://images.deepai.org/art-image/63caa58d69634274b2e177698a0d9d08/for-my-ecommecre-website-banner-a-perfume-wit_J9cMbpC.jpg",
        name: "Rose Elegance",
        color: "Pink",
        type:"mild",
        price: 2000,
        dealOfTheDayPrice: 2000,
        brand: "Floral Essence",
        outfit: "Women",
        description: "Rose Elegance is a fresh delicate and romantic fragrance, blending the softness of rose petals with hints of jasmine and vanilla. This fragrance is perfect for daily wear and adds a feminine touch to any outfit.",
        rating: 4.7,
        reviewNumber: 150,
        availability: "In stock",
        stock: 25
    },
    {
        id: 3,
        image: "https://images.deepai.org/art-image/63caa58d69634274b2e177698a0d9d08/for-my-ecommecre-website-banner-a-perfume-wit_J9cMbpC.jpg",
        name: "Ocean Breeze",
        color: "Blue",
        type:"moderate",
        price: 2700,
        dealOfTheDayPrice: 2400,
        brand: "Breeze Co.",
        outfit: "Women",
        description: "Ocean Breeze is a fresh and invigorating fragrance that captures the essence of the sea with notes of citrus, marine accord, and a hint of floral. Perfect for those who love light, breezy perfumes.",
        rating: 4.6,
        reviewNumber: 180,
        availability: "In stock",
        stock: 30
    },
    {
        id: 4,
        image: "https://images.deepai.org/art-image/41178d40a5df4e288bda15858e81dbad/perfume-name-lethered-gold-74c819.jpg",
        name: "Citrus Zest",
        color: "Yellow",
        type:"mild",
        price: 1900,
        dealOfTheDayPrice: 1700,
        brand: "Zest Scents",
        outfit: "Men",
        description: "Citrus Zest is a refreshing and zesty fragrance, bursting with the bright and tangy scents of lemon, lime, and grapefruit. This fragrance is perfect for daytime wear, adding an energizing touch to your routine.",
        rating: 4.5,
        reviewNumber: 90,
        availability: "In stock",
        stock: 40
    },
    {
        id: 5,
        image: "https://images.deepai.org/art-image/41178d40a5df4e288bda15858e81dbad/perfume-name-lethered-gold-74c819.jpg",
        name: "Vanilla Delight",
        color: "Cream",
        type:"moderate",
        price: 2800,
        dealOfTheDayPrice: 2500,
        brand: "Sweet Essence",
        outfit: "Women",
        description: "Vanilla Delight is a warm and comforting fragrance with rich vanilla notes, blended with caramel and a touch of musk. This gourmand perfume is perfect for those who enjoy sweet, cozy scents.",
        rating: 4.8,
        reviewNumber: 210,
        availability: "In stock",
        stock: 15
    },
    {
        id: 6,
        image: "https://images.deepai.org/art-image/41178d40a5df4e288bda15858e81dbad/perfume-name-lethered-gold-74c819.jpg",
        name: "Black Leather",
        color: "Black",
        type:"strong",
        price: 3800,
        dealOfTheDayPrice: 3500,
        brand: "Leather Craft",
        outfit: "Men",
        description: "Black Leather is a bold, masculine fragrance that combines rich leather with spicy notes of black pepper and cardamom. This sophisticated scent is perfect for the confident, modern man.",
        rating: 4.9,
        reviewNumber: 100,
        availability: "In stock",
        stock: 12
    },
    {
        id: 7,
        image: "https://images.deepai.org/art-image/41178d40a5df4e288bda15858e81dbad/perfume-name-lethered-gold-74c819.jpg",
        name: "Lily Blossom",
        color: "White",
        type:"mild",
        price: 3300,
        dealOfTheDayPrice: 3100,
        brand: "Floral Essence",
        outfit: "Women",
        description: "Lily Blossom is a gentle and floral fragrance with the sweet aroma of lily of the valley, mixed with hints of jasmine and rose. This perfume embodies grace and elegance, ideal for special occasions.",
        rating: 4.7,
        reviewNumber: 160,
        availability: "In stock",
        stock: 20
    },
    {
        id: 8,
        image: "https://images.deepai.org/art-image/85472a4b612848f189aaff7f377bba16/perfume-name-lethered-gold-cac113.jpg",
        name: "Sandalwood Breeze",
        color: "Beige",
        type:"moderate",
        price: 3400,
        dealOfTheDayPrice: 3200,
        brand: "Wood Essence",
        outfit: "Men",
        description: "Sandalwood Breeze offers a warm and earthy scent, with the rich essence of sandalwood mixed with a subtle touch of spice. Perfect for those who appreciate deep, woody fragrances.",
        rating: 4.6,
        reviewNumber: 210,
        availability: "In stock",
        stock: 18
    },
    {
        id: 9,
        image: "https://images.deepai.org/art-image/85472a4b612848f189aaff7f377bba16/perfume-name-lethered-gold-cac113.jpg",
        name: "Lavender Dream",
        color: "Purple",
        type:"strong",
        price: 2500,
        dealOfTheDayPrice: 2300,
        brand: "Calm Scents",
        outfit: "Women",
        description: "Lavender Dream is a calming fragrance that blends the soothing essence of lavender with notes of chamomile and mint. This fragrance is perfect for relaxation and creating a peaceful atmosphere.",
        rating: 4.8,
        reviewNumber: 130,
        availability: "In stock",
        stock: 22
    },
    {
        id: 10,
        image: "https://images.deepai.org/art-image/85472a4b612848f189aaff7f377bba16/perfume-name-lethered-gold-cac113.jpg",
        name: "Spicy Noir",
        color: "Dark Red",
        type:"strong",
        price: 3100,
        dealOfTheDayPrice: 2800,
        brand: "Noir Essence",
        outfit: "Men",
        description: "Spicy Noir is an intense and bold fragrance, blending spicy cinnamon with rich amber and a touch of musk. Perfect for evening wear, this fragrance exudes a sense of adventure and allure.",
        rating: 4.7,
        reviewNumber: 190,
        availability: "In stock",
        stock: 14
    },
    {
        id: 11,
        image: "https://images.deepai.org/art-image/95378cad87c84b468bbb724649bb98eb/perfume-name-amber-assence.jpg",
        name: "Amber Essence",
        color: "Amber",
        type:"moderate",
        price: 4000,
        dealOfTheDayPrice: 3800,
        brand: "Essence Co.",
        outfit: "Men",
        description: "Amber Essence is a luxurious fragrance with the rich, warm scent of amber and a hint of tobacco. Perfect for formal events or evening wear, this scent is bold and elegant.",
        rating: 4.9,
        reviewNumber: 220,
        availability: "In stock",
        stock: 8
    },
    {
        id: 12,
        image: "https://images.deepai.org/art-image/010e02650bd842d48fd70000cfd90702/perfume-name-ocean.jpg",
        name: "Eternal Bloom",
        color: "Rose Gold",
        type:"strong",
        price: 2900,
        dealOfTheDayPrice: 2700,
        brand: "Bloom Essence",
        outfit: "Women",
        description: "Eternal Bloom is a timeless fragrance that combines the fresh scent of blooming flowers with soft hints of musk and vanilla. Perfect for daytime wear or as a signature scent.",
        rating: 4.7,
        reviewNumber: 175,
        availability: "In stock",
        stock: 20
    },
    {
        id: 13,
        image: "https://images.deepai.org/art-image/010e02650bd842d48fd70000cfd90702/perfume-name-ocean.jpg",
        name: "Midnight Spice",
        color: "Dark Purple",
        type:"moderate",
        price: 3100,
        dealOfTheDayPrice: 2900,
        brand: "Spice Noir",
        outfit: "Men",
        description: "Midnight Spice is an exotic fragrance with a mix of warm spices, such as cinnamon and cloves, blended with woody notes. It's perfect for nighttime adventures or a special evening.",
        rating: 4.6,
        reviewNumber: 150,
        availability: "In stock",
        stock: 15
    },
    {
        id: 14,
        image: "https://images.deepai.org/art-image/010e02650bd842d48fd70000cfd90702/perfume-name-ocean.jpg",
        name: "Jasmine Allure",
        color: "Gold",
        type:"mild",
        price: 3300,
        dealOfTheDayPrice: 3100,
        brand: "Floral Essence",
        outfit: "Women",
        description: "Jasmine Allure is a captivating fragrance that celebrates the essence of jasmine, mixed with citrus and a touch of musk. This perfume is perfect for those who love elegant, floral scents.",
        rating: 4.8,
        reviewNumber: 190,
        availability: "In stock",
        stock: 25
    },
    {
        id: 15,
        image: "https://images.deepai.org/art-image/41178d40a5df4e288bda15858e81dbad/perfume-name-lethered-gold-74c819.jpg",
        name: "Leathered Gold",
        color: "Gold",
        type:"moderate",
        price: 4000,
        dealOfTheDayPrice: 3800,
        brand: "Scents",
        outfit: "Men",
        description: "Leathered Gold is a luxurious fragrance with the rich scent of leather, blended with a hint of gold amber and smoky undertones. Perfect for the sophisticated man with a refined taste.",
        rating: 4.9,
        reviewNumber: 220,
        availability: "In stock",
        stock: 10
    },
    {
        id: 16,
        image: "https://images.deepai.org/art-image/b33b981561d2441f959d59c849e471f0/floral-perfume-name.jpg",
        name: "Floral Fantasy",
        color: "Pink",
        type:"mild",
        price: 3000,
        dealOfTheDayPrice: 2800,
        brand: "Floral Essence",
        outfit: "Women",
        description: "Floral Fantasy is a delicate and fresh scent that combines the soft notes of roses and peonies with hints of green leaves. This fragrance is perfect for everyday wear, offering a light and airy feel.",
        rating: 4.7,
        reviewNumber: 210,
        availability: "In stock",
        stock: 18
    },
    {
        id: 17,
        image: "https://images.deepai.org/art-image/b33b981561d2441f959d59c849e471f0/floral-perfume-name.jpg",
        name: "Tobacco Leaf",
        color: "Brown",
        type:"strong",
        price: 4500,
        dealOfTheDayPrice: 3300,
        brand: "Wood Essence",
        outfit: "Men",
        description: "Tobacco Leaf is a smoky and earthy fragrance with notes of tobacco, leather, and amber. A bold and mature scent, ideal for evening wear or formal occasions.",
        rating: 4.8,
        reviewNumber: 160,
        availability: "In stock",
        stock: 12
    },
    {
        id: 18,
        image: "https://images.deepai.org/art-image/ba0a60ef80e14c8aad277f99e7c98108/lemon-perfume-name.jpg",
        name: "Lemon Breeze",
        color: "Yellow",
        type:"mild",
        price: 2200,
        dealOfTheDayPrice: 2000,
        brand: "Citrus Essence",
        outfit: "Men",
        description: "Lemon Breeze is a crisp and refreshing fragrance, with the zesty essence of lemon and lime, combined with soft floral notes. Perfect for summer days or as an uplifting daytime fragrance.",
        rating: 4.5,
        reviewNumber: 180,
        availability: "In stock",
        stock: 30
    },
    {
        id: 19,
        image: "https://images.deepai.org/art-image/8b47caf7f037484f8c47094f4ccce444/red-bottle-perfume-name.jpg",
        name: "Vanilla Spice",
        color: "Red",
        type:"strong",
        price: 4000,
        dealOfTheDayPrice: 2900,
        brand: "Sweet Essence",
        outfit: "Women",
        description: "Vanilla Spice is a warm and inviting fragrance, with the sweet richness of vanilla combined with spicy notes of cinnamon and nutmeg. Ideal for colder seasons or cozy evenings.",
        rating: 4.6,
        reviewNumber: 160,
        availability: "In stock",
        stock: 22
    },
    {
        id: 20,
        image: "https://images.unsplash.com/photo-1590156221187-1710315f710b?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "White Musk",
        color: "White",
        type:"moderate",
        price: 3200,
        dealOfTheDayPrice: 3000,
        brand: "Musk Essence",
        outfit: "Women",
        description: "White Musk is a soft and sensual fragrance that combines clean musk with floral notes of jasmine and rose. A perfect choice for anyone who enjoys understated, elegant perfumes.",
        rating: 4.7,
        reviewNumber: 170,
        availability: "In stock",
        stock: 10
    },
    {
        id: 21,
        image: "https://images.unsplash.com/photo-1590156221187-1710315f710b?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Ocean Waves",
        color: "Light Blue",
        type:"moderate",
        price: 2200,
        dealOfTheDayPrice: 2000,
        brand: "Breeze Co.",
        outfit: "Women",
        description: "Ocean Waves is a fresh and uplifting fragrance that captures the essence of the ocean breeze with aquatic notes and a hint of citrus. Perfect for those who enjoy refreshing and light perfumes.",
        rating: 4.7,
        reviewNumber: 190,
        availability: "In stock",
        stock: 20
    },
    {
        id: 22,
        image: "https://images.unsplash.com/photo-1593487568720-92097fb460fb?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Winter Woods",
        color: "Forest Green",
        price: 3600,
        type:"moderate",
        dealOfTheDayPrice: 3400,
        brand: "Wood Essence",
        outfit: "Men",
        description: "Winter Woods is a deep, woody fragrance that combines the rich scent of pine and cedarwood with a touch of warm amber. Perfect for cold-weather days, this fragrance will evoke the feeling of a winter forest.",
        rating: 4.8,
        reviewNumber: 200,
        availability: "In stock",
        stock: 8
    },
    {
        id: 23,
        image: "https://images.unsplash.com/photo-1593487568720-92097fb460fb?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Sunset Blossom",
        color: "Orange",
        price: 2500,
        type:"moderate",
        dealOfTheDayPrice: 2300,
        brand: "Bloom Essence",
        outfit: "Women",
        description: "Sunset Blossom is a vibrant and floral fragrance that blends the warmth of orange blossoms with soft notes of peach and vanilla. This fragrance is perfect for evening outings or romantic occasions.",
        rating: 4.6,
        reviewNumber: 150,
        availability: "In stock",
        stock: 22
    },
    {
        id: 24,
        image: "https://images.unsplash.com/photo-1593487568720-92097fb460fb?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Mystic Noir",
        color: "Black",
        price: 3800,
        type:"mild",
        dealOfTheDayPrice: 3500,
        brand: "Noir Essence",
        outfit: "Men",
        description: "Mystic Noir is a dark and mysterious fragrance, blending rich notes of oud, incense, and blackberries. A bold, daring scent for the confident man who enjoys exotic and unique perfumes.",
        rating: 4.8,
        reviewNumber: 140,
        availability: "In stock",
        stock: 10
    },
    {
        id: 25,
        image: "https://images.unsplash.com/photo-1623742310401-d8057c3c43c8?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Sweet Peach",
        color: "Peach",
        price: 2300,
        type:"mild",
        dealOfTheDayPrice: 2100,
        brand: "Floral Essence",
        outfit: "Women",
        description: "Sweet Peach is a fruity, fresh fragrance with the juicy sweetness of peaches, blended with a hint of vanilla and floral notes. Perfect for summer or casual wear, this fragrance will keep you feeling fresh.",
        rating: 4.7,
        reviewNumber: 160,
        availability: "In stock",
        stock: 25
    },
    {
        id: 26,
        image: "https://images.unsplash.com/photo-1623742310401-d8057c3c43c8?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Midnight Velvet",
        color: "Purple",
        price: 4300,
        type:"strong",
        dealOfTheDayPrice: 3100,
        brand: "Velvet Scents",
        outfit: "Women",
        description: "Midnight Velvet is a deep, rich fragrance that combines floral notes with warm amber and vanilla. Ideal for evening wear, this fragrance exudes elegance and sophistication.",
        rating: 4.9,
        reviewNumber: 180,
        availability: "In stock",
        stock: 15
    },
    {
        id: 27,
        image: "https://images.unsplash.com/photo-1533603208986-24fd819e718a?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Bold Spice",
        color: "Red",
        price: 3200,
        type:"strong",
        dealOfTheDayPrice: 3000,
        brand: "Spice Essence",
        outfit: "Men",
        description: "Bold Spice is an intense fragrance that combines spicy notes of pepper and cinnamon with a touch of tobacco and leather. This fragrance is perfect for the man who enjoys bold, spicy scents.",
        rating: 4.7,
        reviewNumber: 170,
        availability: "In stock",
        stock: 20
    },
    {
        id: 28,
        image: "https://images.unsplash.com/photo-1533603208986-24fd819e718a?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Garden Bloom",
        color: "Green",
        price: 2400,
        type:"mild",
        dealOfTheDayPrice: 2200,
        brand: "Floral Essence",
        outfit: "Women",
        description: "Garden Bloom is a refreshing and light fragrance, with the fresh scent of spring flowers and a hint of greenery. Perfect for daytime wear, this fragrance will keep you feeling fresh and energized.",
        rating: 4.6,
        reviewNumber: 180,
        availability: "In stock",
        stock: 30
    },
    {
        id: 29,
        image: "https://images.deepai.org/art-image/56932ab73dd549778bb0307f8c5f0b20/perfume-name-royal-oud.jpg",
        name: "Royal Oud",
        color: "Gold",
        price: 4600,
        type:"strong",
        dealOfTheDayPrice: 4200,
        brand: "Royal Scents",
        outfit: "Men",
        description: "Royal Oud is a rich, luxurious fragrance that combines deep oud wood with spices and a touch of saffron. This fragrance is perfect for those who appreciate bold, sophisticated scents.",
        rating: 4.9,
        reviewNumber: 220,
        availability: "In stock",
        stock: 8
    },
    {
        id: 30,
        image: "https://images.unsplash.com/photo-1533603208986-24fd819e718a?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        name: "Silk Blossom",
        color: "Pink",
        price: 2900,
        type:"mild",
        dealOfTheDayPrice: 2700,
        brand: "Velvet Scents",
        outfit: "Women",
        description: "Silk Blossom is a soft and delicate fragrance with floral notes of jasmine and cherry blossom, combined with a hint of sweet vanilla. A perfect fragrance for those who enjoy light and elegant scents.",
        rating: 4.8,
        reviewNumber: 190,
        availability: "In stock",
        stock: 25
    }
]
export default Data;








